---
name: CI

# yamllint disable-line rule:truthy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: syphar/restore-virtualenv@v1
        id: venv-cache
      - uses: abatilo/actions-poetry@v2.1.2
        if: steps.setup-venv.outputs.cache-hit != 'true'
      - name: Install Python dependencies
        run: poetry install -vv
        if: steps.setup-venv.outputs.cache-hit != 'true'

      - run: poetry run flake8
      - run: poetry run black --check .
      - run: poetry run pyre --noninteractive
      - run: poetry run green --run-coverage
      - run: poetry run coverage xml

      - uses: codecov/codecov-action@v4
